import oracledb from 'oracledb';
import { config } from '../config/env';
import logger from '../utils/logger';

export class DatabaseService {
  private pool: oracledb.Pool | null = null;

  async initialize(): Promise<void> {
    if (!config.db.user || !config.db.password || !config.db.connectString) {
      if (config.nodeEnv !== 'production') {
        logger.warn('Oracle DB is not configured; metadata persistence will use the in-memory fallback.');
      }
      return;
    }

    oracledb.outFormat = oracledb.OUT_FORMAT_OBJECT;
    this.pool = await oracledb.createPool({
      user: config.db.user,
      password: config.db.password,
      connectString: config.db.connectString,
      poolMin: 1,
      poolMax: 4,
      poolIncrement: 1,
      queueRequests: true,
      queueTimeout: 60000,
    });

    await this.ensureSchema();
    logger.info('Oracle DB pool initialized');
  }

  async shutdown(): Promise<void> {
    if (this.pool) {
      await this.pool.close(10);
      this.pool = null;
    }
  }

  async getConnection(): Promise<oracledb.Connection> {
    if (!this.pool) {
      throw new Error('Database pool is not initialized');
    }

    return this.pool.getConnection();
  }

  async healthCheck(): Promise<{ configured: boolean; connected: boolean }> {
    if (!this.pool) {
      return { configured: Boolean(config.db.user && config.db.password && config.db.connectString), connected: false };
    }

    try {
      const connection = await this.pool.getConnection();
      await connection.ping();
      await connection.close();
      return { configured: true, connected: true };
    } catch (error) {
      logger.error('Database health check failed', error);
      return { configured: true, connected: false };
    }
  }

  private async ensureSchema(): Promise<void> {
    if (!this.pool) return;

    const connection = await this.pool.getConnection();
    try {
      await connection.execute(`
        CREATE TABLE media (
          id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          uuid VARCHAR2(64) NOT NULL,
          owner_id VARCHAR2(128) NOT NULL,
          room_id VARCHAR2(128),
          filename VARCHAR2(256) NOT NULL,
          original_filename VARCHAR2(256) NOT NULL,
          extension VARCHAR2(32),
          mime_type VARCHAR2(128),
          file_size NUMBER,
          duration NUMBER,
          width NUMBER,
          height NUMBER,
          checksum VARCHAR2(128),
          relative_path VARCHAR2(1024),
          visibility VARCHAR2(32),
          status VARCHAR2(32),
          upload_source VARCHAR2(64),
          created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
          updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
      `);
      await connection.execute(`CREATE INDEX idx_media_uuid ON media (uuid)`);
      await connection.execute(`CREATE INDEX idx_media_owner_id ON media (owner_id)`);
      await connection.execute(`CREATE INDEX idx_media_status ON media (status)`);
      await connection.commit();
    } catch (error) {
      logger.warn('Schema initialization skipped or already exists', error);
    } finally {
      await connection.close();
    }
  }
}
